name: my_fiftyone_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - fiftyone
  - pandas
  - jupyterlab
<<<<<<< HEAD
  - numpy
  - jupyter
=======
  - seaborn
  - pip
  - pip:
      - torch
      - torchvision
      - torchaudio
>>>>>>> ea721c1 (baseline model)
