name: my_fiftyone_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - fiftyone
  - pandas
  - jupyterlab
  - numpy
  - seaborn
  - pip
  - pytorch
  - torchvision
  - torchaudio
